// =============================================================
// helpers/auth.js — Login helpers + user pool (500 real users)
//
// TEST_USERS diisi dari users_seed.csv: 500 user non-admin
// Password semua: Password123!
// Cukup untuk load test (200 VU) dengan 1 user unik per VU.
//
// Untuk stress/spike test (500 VU), tambahkan 500 user lagi:
//   SELECT email FROM users WHERE role='USER'
//   ORDER BY created_at OFFSET 500 LIMIT 500;
// =============================================================

import http from "k6/http";
import { check } from "k6";
import { JSON_HEADERS } from "./config.js";

export function loginREST(baseUrl, email, password) {
  const res = http.post(
    `${baseUrl}/auth/login`,
    JSON.stringify({ email, password }),
    { headers: JSON_HEADERS },
  );
  const ok = check(res, { "login: status 200": (r) => r.status === 200 });
  if (!ok) console.error(`[login REST] FAILED: ${email} → ${res.status}`);
  return ok;
}

export function loginTRPC(baseUrl, email, password) {
  const res = http.post(
    `${baseUrl}/auth.login`,
    JSON.stringify({ email, password }),  // ← raw, no wrapper
    { headers: JSON_HEADERS },
  );
  const ok = check(res, { "login: status 200": (r) => r.status === 200 });
  if (!ok) console.error(`[login tRPC] FAILED: ${email} → ${res.status}`);
  return ok;
}

export function login(apiType, baseUrl, email, password) {
  if (apiType === "rest") return loginREST(baseUrl, email, password);
  return loginTRPC(baseUrl, email, password);
}

export function logoutREST(baseUrl) {
  const res = http.post(`${baseUrl}/auth/logout`, null, {
    headers: JSON_HEADERS,
  });
  check(res, { "logout: status 200": (r) => r.status === 200 });
}

export function logoutTRPC(baseUrl) {
  const res = http.post(`${baseUrl}/auth.logout`, JSON.stringify({}), {
    headers: JSON_HEADERS,
  });
  check(res, { "logout: status 200": (r) => r.status === 200 });
}

export function logout(apiType, baseUrl) {
  if (apiType === "rest") return logoutREST(baseUrl);
  return logoutTRPC(baseUrl);
}

// =============================================================
// TEST USER POOL — 500 user nyata dari users_seed.csv
// Semua role USER, password: Password123!
// =============================================================
export const TEST_USERS = [
  "indah.firdaus242@hotmail.com",
  "yusuf.santoso482@gmail.com",
  "hani.santoso244@hotmail.com",
  "eko.wardana116@outlook.com",
  "sena.karim52@hotmail.com",
  "widi.rahardjo483@yahoo.com",
  "yanti.nugroho245@outlook.com",
  "jasmine.gunawan117@gmail.com",
  "tono.hakim243@gmail.com",
  "zahra.suharto1@outlook.com",
  "erna.wardana2@gmail.com",
  "mukti.wahyudi3@gmail.com",
  "prita.wahyudi4@outlook.com",
  "farhan.firdaus484@outlook.com",
  "luki.hartono6@hotmail.com",
  "joko.subagyo7@outlook.com",
  "ulfa.rachmat8@hotmail.com",
  "vina.rahardjo9@outlook.com",
  "widi.firdaus10@hotmail.com",
  "farhan.subagyo11@hotmail.com",
  "yoga.saputra12@gmail.com",
  "jasmine.purnomo13@gmail.com",
  "udin.setiawan14@outlook.com",
  "dinda.utama15@outlook.com",
  "dewi.tanjung16@gmail.com",
  "hani.halim17@hotmail.com",
  "tono.gunawan18@hotmail.com",
  "reza.zainal19@yahoo.com",
  "hafiz.suharto20@outlook.com",
  "nanda.firdaus485@gmail.com",
  "maya.hidayat22@yahoo.com",
  "udin.hartono23@gmail.com",
  "siti.wibowo24@gmail.com",
  "wahyu.wijaya25@gmail.com",
  "teguh.halim26@gmail.com",
  "leo.kusuma27@yahoo.com",
  "umar.wibowo28@outlook.com",
  "mukti.mansur29@gmail.com",
  "ivan.setiawan30@hotmail.com",
  "luki.latif31@outlook.com",
  "sari.maulana32@yahoo.com",
  "joko.wijaya33@outlook.com",
  "zulfa.purnomo34@outlook.com",
  "kiki.rachmat35@outlook.com",
  "zaki.iskandar36@yahoo.com",
  "kiki.wibowo37@gmail.com",
  "erna.wijaya38@outlook.com",
  "bella.rahardjo39@gmail.com",
  "udin.maulana40@gmail.com",
  "citra.wibowo41@gmail.com",
  "sela.hakim42@yahoo.com",
  "zahra.rahardjo43@gmail.com",
  "luki.wardana44@gmail.com",
  "putri.hidayat45@gmail.com",
  "wawan.wardana46@hotmail.com",
  "eko.setiawan47@yahoo.com",
  "leo.firdaus48@yahoo.com",
  "agus.hartono49@hotmail.com",
  "hafiz.mansur50@outlook.com",
  "indah.setiawan51@gmail.com",
  "leo.utama241@gmail.com",
  "hafiz.gunawan486@yahoo.com",
  "nisa.rachmat54@hotmail.com",
  "zaki.tanjung55@yahoo.com",
  "luki.utama56@outlook.com",
  "fauzi.kusuma57@yahoo.com",
  "dinda.iskandar58@yahoo.com",
  "arif.wijaya59@outlook.com",
  "bella.hakim60@gmail.com",
  "prima.santoso61@gmail.com",
  "nanda.salim62@outlook.com",
  "zahra.setiawan63@hotmail.com",
  "widi.wardana64@hotmail.com",
  "tasya.hartono65@hotmail.com",
  "dedi.siregar66@yahoo.com",
  "bagas.subagyo67@hotmail.com",
  "eko.subagyo68@hotmail.com",
  "nisa.maulana69@hotmail.com",
  "bagas.iskandar70@gmail.com",
  "kartika.firdaus71@outlook.com",
  "yusuf.tanjung72@gmail.com",
  "yusuf.santoso73@yahoo.com",
  "indah.latif74@yahoo.com",
  "prita.utama75@gmail.com",
  "widi.hakim76@outlook.com",
  "tasya.hakim77@outlook.com",
  "rafi.hartono78@hotmail.com",
  "vina.utama79@outlook.com",
  "jasmine.pratama80@hotmail.com",
  "fitri.wibowo81@yahoo.com",
  "umar.zainal82@outlook.com",
  "nisa.wardana83@outlook.com",
  "naufal.purnomo84@hotmail.com",
  "rafi.halim85@hotmail.com",
  "wawan.karim86@gmail.com",
  "zahra.rahardjo87@outlook.com",
  "ika.tanjung88@yahoo.com",
  "prima.wijaya89@gmail.com",
  "umar.hartono90@hotmail.com",
  "udin.subagyo91@yahoo.com",
  "kiki.kurniawan92@gmail.com",
  "dinda.iskandar93@hotmail.com",
  "cahyo.mansur94@outlook.com",
  "fauzi.zainal95@outlook.com",
  "indah.salim96@outlook.com",
  "ivan.susanto97@outlook.com",
  "vero.rahardjo98@outlook.com",
  "erna.tanjung99@hotmail.com",
  "tono.salim100@yahoo.com",
  "kartika.firdaus101@yahoo.com",
  "fauzi.setiawan102@gmail.com",
  "andi.kusuma103@hotmail.com",
  "indah.siregar104@gmail.com",
  "kevin.gunawan105@gmail.com",
  "bagas.salim106@yahoo.com",
  "indah.halim107@hotmail.com",
  "budi.wahyudi108@hotmail.com",
  "zaki.rahardjo109@gmail.com",
  "wawan.hartono110@outlook.com",
  "andi.salim111@gmail.com",
  "sena.gunawan112@outlook.com",
  "dedi.subagyo113@hotmail.com",
  "leo.iskandar114@hotmail.com",
  "bella.salim5@hotmail.com",
  "siti.utama490@gmail.com",
  "widi.maulana487@hotmail.com",
  "andi.wibowo118@gmail.com",
  "siti.wahyudi119@gmail.com",
  "rafi.halim120@outlook.com",
  "wahyu.saputra121@hotmail.com",
  "reza.purnomo122@outlook.com",
  "citra.salim123@yahoo.com",
  "sari.zainal124@yahoo.com",
  "prima.rachmat125@outlook.com",
  "leo.kusuma126@hotmail.com",
  "rizky.iskandar127@yahoo.com",
  "umar.hartono128@hotmail.com",
  "kevin.purnomo129@gmail.com",
  "gita.hartono130@gmail.com",
  "prima.wibowo131@gmail.com",
  "tono.santoso132@hotmail.com",
  "juli.karim133@gmail.com",
  "lina.subagyo134@yahoo.com",
  "ika.kusuma135@gmail.com",
  "tasya.gunawan136@yahoo.com",
  "andi.iskandar137@yahoo.com",
  "fauzi.nugroho138@hotmail.com",
  "rafi.karim139@hotmail.com",
  "sari.salim140@gmail.com",
  "sela.wijaya141@yahoo.com",
  "mita.halim142@gmail.com",
  "sena.wahyudi143@hotmail.com",
  "umar.wijaya144@hotmail.com",
  "indah.subagyo145@gmail.com",
  "citra.latif146@gmail.com",
  "zahra.wibowo147@gmail.com",
  "reza.gunawan148@hotmail.com",
  "zaki.wardana149@outlook.com",
  "kevin.nugroho150@hotmail.com",
  "zulfa.pratama151@yahoo.com",
  "indah.iskandar152@gmail.com",
  "ika.karim153@hotmail.com",
  "reza.pratama154@hotmail.com",
  "gita.latif155@yahoo.com",
  "rafi.nugroho156@yahoo.com",
  "wahyu.maulana157@yahoo.com",
  "hani.salim158@outlook.com",
  "dinda.iskandar159@hotmail.com",
  "tono.latif160@hotmail.com",
  "erna.setiawan161@hotmail.com",
  "dedi.halim162@hotmail.com",
  "widi.kurniawan163@yahoo.com",
  "citra.saputra164@yahoo.com",
  "maya.santoso165@outlook.com",
  "rafi.suharto166@outlook.com",
  "teguh.halim167@outlook.com",
  "hafiz.hakim168@yahoo.com",
  "juli.rachmat169@gmail.com",
  "okta.rahardjo170@hotmail.com",
  "sena.wardana171@outlook.com",
  "budi.hidayat172@outlook.com",
  "yusuf.siregar173@yahoo.com",
  "indah.wijaya174@hotmail.com",
  "nanda.mansur175@hotmail.com",
  "wawan.rachmat176@outlook.com",
  "wawan.rachmat177@hotmail.com",
  "prima.iskandar178@gmail.com",
  "ivan.rachmat179@gmail.com",
  "aditya.wibowo180@gmail.com",
  "zaki.wibowo181@outlook.com",
  "nisa.susanto182@outlook.com",
  "vero.pratama183@yahoo.com",
  "sena.pratama184@gmail.com",
  "kiki.mansur185@yahoo.com",
  "teguh.halim186@outlook.com",
  "galih.wardana187@gmail.com",
  "vita.mansur188@outlook.com",
  "udin.wibowo189@yahoo.com",
  "vina.purnomo190@yahoo.com",
  "sari.wijaya191@hotmail.com",
  "zahra.suharto192@gmail.com",
  "teguh.kusuma193@outlook.com",
  "leo.siregar194@yahoo.com",
  "putri.kurniawan195@yahoo.com",
  "irfan.purnomo196@gmail.com",
  "ulfa.subagyo197@gmail.com",
  "prima.wibowo198@hotmail.com",
  "joko.saputra199@yahoo.com",
  "hendra.siregar200@outlook.com",
  "zaki.subagyo201@outlook.com",
  "erna.gunawan202@yahoo.com",
  "juli.kurniawan203@gmail.com",
  "yoga.hartono204@gmail.com",
  "bella.siregar205@yahoo.com",
  "naufal.purnomo206@gmail.com",
  "kiki.firdaus207@yahoo.com",
  "hafiz.hartono208@gmail.com",
  "hendra.wahyudi209@outlook.com",
  "hani.hakim210@outlook.com",
  "vita.susanto211@hotmail.com",
  "teguh.siregar212@yahoo.com",
  "maya.karim213@outlook.com",
  "dewi.nugroho214@hotmail.com",
  "wahyu.iskandar215@hotmail.com",
  "umar.siregar216@hotmail.com",
  "bella.hartono217@hotmail.com",
  "leo.wahyudi218@yahoo.com",
  "zulfa.wahyudi219@hotmail.com",
  "ika.kusuma220@hotmail.com",
  "zaki.firdaus221@yahoo.com",
  "rafi.pratama222@outlook.com",
  "sela.zainal223@yahoo.com",
  "gita.santoso224@hotmail.com",
  "maya.setiawan225@hotmail.com",
  "kiki.nugroho226@yahoo.com",
  "dewi.kusuma227@yahoo.com",
  "juli.suharto228@hotmail.com",
  "hani.rachmat229@yahoo.com",
  "indah.hidayat230@hotmail.com",
  "bagas.siregar231@gmail.com",
  "kiki.zainal232@yahoo.com",
  "ulfa.firdaus233@hotmail.com",
  "dinda.maulana234@hotmail.com",
  "hafiz.wahyudi235@outlook.com",
  "cahyo.salim236@yahoo.com",
  "sena.purnomo237@hotmail.com",
  "hafiz.tanjung238@outlook.com",
  "erna.iskandar239@gmail.com",
  "maya.wahyudi115@hotmail.com",
  "bagas.kusuma21@gmail.com",
  "prima.hidayat53@yahoo.com",
  "hani.subagyo240@yahoo.com",
  "zahra.siregar489@hotmail.com",
  "mukti.gunawan488@hotmail.com",
  "gita.rahardjo246@gmail.com",
  "aditya.subagyo247@gmail.com",
  "luki.maulana248@hotmail.com",
  "nisa.wardana249@outlook.com",
  "vero.rachmat250@gmail.com",
  "bagas.iskandar251@yahoo.com",
  "dewi.firdaus252@yahoo.com",
  "sena.subagyo253@yahoo.com",
  "leo.wibowo254@hotmail.com",
  "kartika.purnomo255@hotmail.com",
  "bella.santoso256@yahoo.com",
  "zaki.karim257@hotmail.com",
  "tono.gunawan258@hotmail.com",
  "mukti.firdaus259@yahoo.com",
  "galih.santoso260@gmail.com",
  "rafi.setiawan261@gmail.com",
  "luki.nugroho262@outlook.com",
  "udin.wijaya263@gmail.com",
  "vero.wijaya264@hotmail.com",
  "yusuf.wibowo265@yahoo.com",
  "bella.zainal266@gmail.com",
  "sena.latif267@outlook.com",
  "wawan.wahyudi268@yahoo.com",
  "indah.mansur269@gmail.com",
  "arif.utama270@outlook.com",
  "arif.gunawan271@outlook.com",
  "hani.santoso272@outlook.com",
  "ulfa.karim273@yahoo.com",
  "fitri.firdaus274@hotmail.com",
  "hani.rahardjo275@outlook.com",
  "zulfa.tanjung276@hotmail.com",
  "indah.rahardjo277@gmail.com",
  "tono.latif278@gmail.com",
  "prima.setiawan279@hotmail.com",
  "andi.wahyudi280@outlook.com",
  "vina.kusuma281@yahoo.com",
  "vita.santoso282@yahoo.com",
  "dedi.saputra283@hotmail.com",
  "maya.wijaya284@yahoo.com",
  "arif.tanjung285@hotmail.com",
  "ivan.salim286@hotmail.com",
  "umar.gunawan287@gmail.com",
  "bagas.wardana288@gmail.com",
  "nanda.rahardjo289@outlook.com",
  "maya.hakim290@hotmail.com",
  "bella.hidayat291@yahoo.com",
  "nanda.mansur292@outlook.com",
  "fauzi.rachmat293@gmail.com",
  "okta.latif294@yahoo.com",
  "zulfa.utama295@yahoo.com",
  "vita.rachmat296@gmail.com",
  "ika.wahyudi297@hotmail.com",
  "vero.susanto298@yahoo.com",
  "putri.halim299@gmail.com",
  "prita.halim300@yahoo.com",
  "andi.siregar301@yahoo.com",
  "teguh.mansur302@hotmail.com",
  "eko.hidayat303@outlook.com",
  "bagas.karim304@gmail.com",
  "vita.maulana305@gmail.com",
  "tasya.iskandar306@yahoo.com",
  "reza.saputra307@gmail.com",
  "galih.rachmat308@hotmail.com",
  "hafiz.subagyo309@hotmail.com",
  "wahyu.santoso310@hotmail.com",
  "lina.susanto311@gmail.com",
  "sari.pratama312@yahoo.com",
  "vero.pratama313@gmail.com",
  "fauzi.susanto314@outlook.com",
  "sari.halim315@gmail.com",
  "vina.purnomo316@yahoo.com",
  "fauzi.kurniawan317@hotmail.com",
  "lina.siregar318@outlook.com",
  "fauzi.wibowo319@hotmail.com",
  "erna.wijaya320@gmail.com",
  "ika.hartono321@gmail.com",
  "okta.karim322@hotmail.com",
  "budi.tanjung323@yahoo.com",
  "galih.hakim324@yahoo.com",
  "sena.susanto325@outlook.com",
  "hani.wardana326@outlook.com",
  "yusuf.saputra327@outlook.com",
  "irfan.nugroho328@outlook.com",
  "aditya.tanjung329@outlook.com",
  "erna.firdaus330@hotmail.com",
  "dewi.utama331@outlook.com",
  "tono.wahyudi332@yahoo.com",
  "yoga.rachmat333@gmail.com",
  "prita.firdaus334@yahoo.com",
  "leo.siregar335@hotmail.com",
  "putri.maulana336@hotmail.com",
  "widi.salim337@gmail.com",
  "zahra.pratama338@yahoo.com",
  "siti.suharto339@hotmail.com",
  "arif.utama340@hotmail.com",
  "galih.hakim341@gmail.com",
  "galih.gunawan342@hotmail.com",
  "gita.zainal343@hotmail.com",
  "agus.purnomo344@outlook.com",
  "cahyo.purnomo345@outlook.com",
  "indah.pratama346@gmail.com",
  "lina.hartono347@outlook.com",
  "citra.mansur348@outlook.com",
  "tono.saputra349@hotmail.com",
  "leo.hidayat350@outlook.com",
  "dedi.firdaus351@hotmail.com",
  "tono.utama352@outlook.com",
  "vero.maulana353@hotmail.com",
  "farhan.wardana354@hotmail.com",
  "aditya.wardana355@yahoo.com",
  "udin.halim356@gmail.com",
  "gita.maulana357@yahoo.com",
  "lina.firdaus358@gmail.com",
  "hendra.salim359@gmail.com",
  "andi.wahyudi360@hotmail.com",
  "wahyu.kusuma361@outlook.com",
  "yanti.mansur362@gmail.com",
  "teguh.halim363@outlook.com",
  "zaki.rahardjo364@gmail.com",
  "yusuf.subagyo365@yahoo.com",
  "sena.pratama366@gmail.com",
  "budi.siregar367@outlook.com",
  "jasmine.hidayat368@hotmail.com",
  "mukti.subagyo369@outlook.com",
  "tasya.setiawan370@hotmail.com",
  "dedi.salim371@yahoo.com",
  "kiki.rachmat372@outlook.com",
  "yoga.karim373@outlook.com",
  "prima.suharto374@outlook.com",
  "joko.tanjung375@hotmail.com",
  "agus.hartono376@hotmail.com",
  "teguh.pratama377@gmail.com",
  "prima.subagyo378@gmail.com",
  "prita.pratama379@gmail.com",
  "prita.santoso380@outlook.com",
  "joko.wardana381@gmail.com",
  "leo.tanjung382@gmail.com",
  "kevin.hidayat383@hotmail.com",
  "dedi.purnomo384@outlook.com",
  "ika.zainal385@gmail.com",
  "gita.hartono386@hotmail.com",
  "yanti.wahyudi387@gmail.com",
  "wawan.kusuma388@gmail.com",
  "gita.kurniawan389@gmail.com",
  "yanti.maulana390@yahoo.com",
  "vina.susanto391@gmail.com",
  "zahra.setiawan392@gmail.com",
  "okta.wardana393@yahoo.com",
  "ika.wijaya394@outlook.com",
  "wahyu.gunawan395@gmail.com",
  "yusuf.siregar396@hotmail.com",
  "zulfa.suharto397@yahoo.com",
  "teguh.karim398@gmail.com",
  "budi.karim399@hotmail.com",
  "tasya.rachmat400@outlook.com",
  "nanda.wibowo401@gmail.com",
  "prima.setiawan402@hotmail.com",
  "naufal.siregar403@outlook.com",
  "yusuf.setiawan404@hotmail.com",
  "ika.rachmat405@outlook.com",
  "indah.rahardjo406@hotmail.com",
  "sena.wibowo407@hotmail.com",
  "cahyo.hartono408@outlook.com",
  "fitri.subagyo409@outlook.com",
  "gita.tanjung410@hotmail.com",
  "sena.iskandar411@gmail.com",
  "ika.kurniawan412@gmail.com",
  "juli.tanjung413@yahoo.com",
  "rafi.salim414@outlook.com",
  "okta.wahyudi415@gmail.com",
  "nisa.utama416@hotmail.com",
  "sena.maulana417@hotmail.com",
  "rafi.wibowo418@hotmail.com",
  "indah.purnomo419@gmail.com",
  "okta.hakim420@yahoo.com",
  "zaki.kusuma421@hotmail.com",
  "juli.mansur422@outlook.com",
  "joko.santoso423@outlook.com",
  "hafiz.susanto424@yahoo.com",
  "wahyu.iskandar425@hotmail.com",
  "prima.siregar426@yahoo.com",
  "bagas.salim427@yahoo.com",
  "sela.hakim428@yahoo.com",
  "sela.utama429@hotmail.com",
  "yoga.wijaya430@yahoo.com",
  "bella.zainal431@hotmail.com",
  "bella.firdaus432@hotmail.com",
  "dinda.rahardjo433@gmail.com",
  "yoga.zainal434@outlook.com",
  "maya.rahardjo435@hotmail.com",
  "kevin.wibowo436@yahoo.com",
  "prita.pratama437@hotmail.com",
  "dinda.rachmat438@hotmail.com",
  "bagas.karim439@yahoo.com",
  "rafi.hidayat440@outlook.com",
  "okta.wahyudi441@yahoo.com",
  "bagas.hakim442@hotmail.com",
  "bella.nugroho443@yahoo.com",
  "putri.wardana444@outlook.com",
  "hafiz.salim445@gmail.com",
  "wawan.latif446@outlook.com",
  "zulfa.kusuma447@outlook.com",
  "mita.siregar448@hotmail.com",
  "reza.rachmat449@gmail.com",
  "umar.latif450@gmail.com",
  "kiki.iskandar451@gmail.com",
  "gita.pratama452@hotmail.com",
  "tasya.siregar453@gmail.com",
  "jasmine.setiawan454@hotmail.com",
  "okta.kusuma455@gmail.com",
  "agus.subagyo456@gmail.com",
  "putri.hakim457@outlook.com",
  "vita.halim458@outlook.com",
  "ika.hidayat459@gmail.com",
  "naufal.wijaya460@hotmail.com",
  "mukti.hartono461@outlook.com",
  "zahra.wahyudi462@outlook.com",
  "indah.salim463@yahoo.com",
  "rafi.kusuma464@outlook.com",
  "yoga.salim465@hotmail.com",
  "okta.tanjung466@hotmail.com",
  "ika.tanjung467@hotmail.com",
  "vina.pratama468@gmail.com",
  "juli.halim469@outlook.com",
  "sela.wibowo470@outlook.com",
  "hendra.hidayat471@yahoo.com",
  "budi.kurniawan472@gmail.com",
  "sena.latif473@gmail.com",
  "agus.setiawan474@gmail.com",
  "prita.susanto475@outlook.com",
  "hafiz.karim476@yahoo.com",
  "nanda.salim477@gmail.com",
  "aditya.susanto478@hotmail.com",
  "okta.iskandar479@gmail.com",
  "agus.utama480@hotmail.com",
  "prita.setiawan481@outlook.com",
  "wawan.kusuma500@hotmail.com",
  "andi.purnomo499@gmail.com",
  "wawan.firdaus498@outlook.com",
  "jasmine.firdaus496@yahoo.com",
  "zulfa.nugroho495@hotmail.com",
  "umar.siregar494@gmail.com",
  "umar.santoso493@yahoo.com",
  "jasmine.wardana492@yahoo.com",
  "rafi.wahyudi491@gmail.com",
  "budi.latif504@hotmail.com",
  "vita.maulana506@outlook.com",
  "arif.iskandar508@hotmail.com",
  "zahra.suharto501@yahoo.com",
  "mita.susanto505@outlook.com",
  "reza.latif502@gmail.com",
  "eko.nugroho497@outlook.com",
  "mita.firdaus503@gmail.com",
  "aditya.firdaus507@yahoo.com",
  "fitri.maulana509@gmail.com",
  "prita.hartono510@yahoo.com",
];

export const ADMIN_USERS = [
  "admin1@zenit.dev",
  "admin2@zenit.dev",
  "admin3@zenit.dev",
  "admin4@zenit.dev",
  "admin5@zenit.dev",
  "admin6@zenit.dev",
  "admin7@zenit.dev",
  "admin8@zenit.dev",
  "admin9@zenit.dev",
  "admin10@zenit.dev",
];

export const TEST_PASSWORD = "Password123!";
export const ADMIN_PASSWORD = "Password123!";

// Distribusi merata — tiap VU dapat user berbeda (1 user per VU utk 200 VU)
export function pickUser(vu) {
  if (TEST_USERS.length === 0) {
    return {
      email: `udin.wahyudi${(vu % 10000) + 1}@proton.me`,
      password: TEST_PASSWORD,
    };
  }
  return { email: TEST_USERS[vu % TEST_USERS.length], password: TEST_PASSWORD };
}

export function pickAdmin(vu) {
  return {
    email: ADMIN_USERS[vu % ADMIN_USERS.length],
    password: ADMIN_PASSWORD,
  };
}
