#!/usr/bin/env bash
# =============================================================
# generate_seed_data.sh — Generate product data untuk k6 test
#
# Jalankan SETELAH seed_barang_final.ts selesai:
#   chmod +x generate_seed_data.sh
#   ./generate_seed_data.sh
#
# Output: generated_product_data.json (di folder yang sama)
# File ini di-load otomatis oleh seed.js saat k6 start.
#
# Env vars yang dipakai (default ke nilai lokal dev):
#   DATABASE_URL  — full connection string (prioritas utama)
#   PGHOST, PGPORT, PGUSER, PGPASSWORD, PGDATABASE — fallback individual
# =============================================================

set -euo pipefail

OUTFILE="$(dirname "$0")/generated_product_data.json"
SLUG_LIMIT=100
CART_LIMIT=30
SLUG_MIN_STOCK=100
CART_MIN_STOCK=50

# ── Resolve DB connection ─────────────────────────────────────
if [ -n "${DATABASE_URL:-}" ]; then
  # Pakai DATABASE_URL langsung (format: postgresql://user:pass@host:port/db)
  PSQL_CMD="psql $DATABASE_URL"
else
  PG_HOST="${PGHOST:-localhost}"
  PG_PORT="${PGPORT:-5432}"
  PG_USER="${PGUSER:-zenit}"
  PG_DB="${PGDATABASE:-ecommerce_db}"
  export PGPASSWORD="${PGPASSWORD:-zenit123}"
  PSQL_CMD="psql -h $PG_HOST -p $PG_PORT -U $PG_USER -d $PG_DB"
fi

echo "=== generate_seed_data.sh ==="
echo "Output: $OUTFILE"
echo ""

# ── Verifikasi koneksi DB ─────────────────────────────────────
echo "🔍 Verifikasi koneksi DB..."
$PSQL_CMD -c "SELECT 1;" -q > /dev/null 2>&1 || {
  echo "❌ Gagal koneksi ke DB."
  echo "   Pastikan DB berjalan dan env DATABASE_URL atau PGHOST/PGUSER/PGPASSWORD/PGDATABASE sudah di-set."
  exit 1
}
echo "✓ Koneksi OK"

# ── Hitung total produk aktif ─────────────────────────────────
TOTAL_ACTIVE=$($PSQL_CMD -t -A -c \
  "SELECT COUNT(*) FROM products WHERE is_active=true;")
echo "  Total produk aktif: $TOTAL_ACTIVE"

if [ "$TOTAL_ACTIVE" -lt 50 ]; then
  echo "❌ Terlalu sedikit produk aktif ($TOTAL_ACTIVE). Pastikan seed_barang_final.ts sudah dijalankan."
  exit 1
fi

# ── Ambil PRODUCT_SLUGS (stock > SLUG_MIN_STOCK, random, limit 100) ──
echo ""
echo "📦 Mengambil $SLUG_LIMIT product slugs (stock > $SLUG_MIN_STOCK)..."
SLUGS_RAW=$($PSQL_CMD -t -A -c \
  "SELECT slug FROM products WHERE is_active=true AND stock>$SLUG_MIN_STOCK ORDER BY random() LIMIT $SLUG_LIMIT;")

SLUG_COUNT=$(echo "$SLUGS_RAW" | grep -c . || true)
echo "  → $SLUG_COUNT slugs ditemukan"

if [ "$SLUG_COUNT" -lt 10 ]; then
  echo "❌ Terlalu sedikit slug ditemukan ($SLUG_COUNT). Cek kolom stock di tabel products."
  exit 1
fi

# ── Ambil PRODUCT_IDS_FOR_CART (stock > CART_MIN_STOCK, random, limit 30) ──
echo ""
echo "🛒 Mengambil $CART_LIMIT product IDs untuk cart (stock > $CART_MIN_STOCK)..."
IDS_RAW=$($PSQL_CMD -t -A -c \
  "SELECT id FROM products WHERE is_active=true AND stock>$CART_MIN_STOCK ORDER BY random() LIMIT $CART_LIMIT;")

ID_COUNT=$(echo "$IDS_RAW" | grep -c . || true)
echo "  → $ID_COUNT product IDs ditemukan"

if [ "$ID_COUNT" -lt 5 ]; then
  echo "❌ Terlalu sedikit produk dengan stok > $CART_MIN_STOCK ($ID_COUNT)."
  echo "   seed_history.ts biasanya reset stock. Cek: SELECT COUNT(*) FROM products WHERE stock>$CART_MIN_STOCK;"
  exit 1
fi

# ── Tulis JSON ────────────────────────────────────────────────
echo ""
echo "📝 Menulis $OUTFILE..."

# Build JSON array dari baris-baris output psql
node - "$OUTFILE" "$SLUGS_RAW" "$IDS_RAW" << 'JSEOF'
const [,, outfile, slugsRaw, idsRaw] = process.argv;
const slugs = slugsRaw.trim().split('\n').map(s => s.trim()).filter(Boolean);
const ids   = idsRaw.trim().split('\n').map(s => s.trim()).filter(Boolean);
const data  = {
  _generated_at: new Date().toISOString(),
  _note: "Auto-generated by generate_seed_data.sh. Jangan edit manual.",
  product_slugs: slugs,
  product_ids_for_cart: ids,
};
require('fs').writeFileSync(outfile, JSON.stringify(data, null, 2));
console.log(`  product_slugs        : ${slugs.length} entries`);
console.log(`  product_ids_for_cart : ${ids.length} entries`);
JSEOF

echo ""
echo "✅ Done! $OUTFILE siap dipakai."
echo ""
echo "Verifikasi:"
echo "  python3 -c \"import json; d=json.load(open('$OUTFILE')); print(f'slugs={len(d[\\\"product_slugs\\\"])}, cart_ids={len(d[\\\"product_ids_for_cart\\\"])}')\""
echo ""
echo "Jalankan smoke test untuk verifikasi data:"
echo "  k6 run --env API=rest run_smoke.js"
