// =============================================================
// helpers/seed-data.js — Test data dari database Zenit Marketplace
//
// File ini sudah diisi dengan data nyata dari:
//   - categories.json  (370 kategori)
//   - users_seed.csv   (500 user non-admin, dari 10.000 total)
//
// PRODUCT_SLUGS dan PRODUCT_IDS_FOR_CART di-load otomatis dari:
//   generated_product_data.json  (di-generate oleh generate_seed_data.sh)
//
// Jika file belum ada, jalankan SETELAH seed DB selesai:
//   chmod +x generate_seed_data.sh
//   ./generate_seed_data.sh
//
// Script akan query DB dan menulis generated_product_data.json di folder ini.
// =============================================================

// =============================================================
// AUTO-LOAD generated product data
// k6 open() baca file saat init — kalau file tidak ada, fallback ke array kosong
// dan test akan warn di console (tapi tidak crash — smoke test akan catch-nya)
// =============================================================
let _generatedData = null;
try {
  _generatedData = JSON.parse(open("./generated_product_data.json"));
} catch (_) {
  // File belum di-generate — jalankan generate_seed_data.sh dulu
  // PRODUCT_SLUGS dan PRODUCT_IDS_FOR_CART akan jadi array kosong
  // s01_browse dan s02_shopping akan skip product-dependent flows
  console.warn(
    "[seed-data] WARNING: generated_product_data.json tidak ditemukan. " +
      "Jalankan ./generate_seed_data.sh setelah seed DB selesai. " +
      "PRODUCT_SLUGS dan PRODUCT_IDS_FOR_CART akan kosong.",
  );
}

// =============================================================
// CATEGORY IDs — Dari categories.json (370 kategori)
// =============================================================
export const CATEGORY_IDS = [
  "cat_aksesoris_kamera_baterai_charger",
  "cat_aksesoris_kamera_case",
  "cat_aksesoris_kamera_cleaning",
  "cat_aksesoris_kamera_dry_box",
  "cat_aksesoris_kamera_microphone",
  "cat_aksesoris_kamera_stabilizer",
  "cat_aksesoris_kamera_strap",
  "cat_aksesoris_kamera_tas",
  "cat_aksesoris_kamera_tripod",
  "cat_al_quran",
  "cat_alkitab",
  "cat_audio_amplifier",
  "cat_audio_earphone",
  "cat_audio_headphone",
  "cat_audio_speaker",
  "cat_audio_tws",
  "cat_audio_voice_recorder",
  "cat_buku_agama_islam",
  "cat_buku_aktivitas",
  "cat_buku_biografi",
  "cat_buku_bisnis",
  "cat_buku_cerita_anak",
  "cat_buku_database",
  "cat_buku_design_graphics",
  "cat_buku_diet",
  "cat_buku_dongeng",
  "cat_buku_ekonomi",
  "cat_buku_ensiklopedia",
  "cat_buku_fotografi",
  "cat_buku_kesehatan_anak",
  "cat_buku_kesuksesan",
  "cat_buku_kewirausahaan",
  "cat_buku_kuliner",
  "cat_buku_latihan_kebugaran",
  "cat_buku_leadership",
  "cat_buku_manajemen",
  "cat_buku_mewarnai",
  "cat_buku_olahraga",
  "cat_buku_programming",
  "cat_buku_resep_kue",
  "cat_buku_resep_masakan",
  "cat_buku_resep_minuman",
  "cat_buku_sd_kelas_1",
  "cat_buku_sd_kelas_4",
  "cat_buku_sejarah",
  "cat_buku_self_improvement",
  "cat_buku_sma_kelas_1",
  "cat_buku_sma_kelas_2",
  "cat_buku_smp_kelas_1",
  "cat_dapur_botol_minum",
  "cat_dapur_cetakan_kue",
  "cat_dapur_coffee_maker",
  "cat_dapur_deep_fryer",
  "cat_dapur_gelas_mug",
  "cat_dapur_gunting",
  "cat_dapur_kompor",
  "cat_dapur_kotak_makan",
  "cat_dapur_loyang",
  "cat_dapur_mangkok",
  "cat_dapur_panci",
  "cat_dapur_parutan",
  "cat_dapur_peeler",
  "cat_dapur_piring",
  "cat_dapur_pisau",
  "cat_dapur_rak",
  "cat_dapur_sendok_garpu",
  "cat_dapur_spatula",
  "cat_dapur_talenan",
  "cat_dapur_termos",
  "cat_dapur_toples",
  "cat_dapur_wajan",
  "cat_drone_kamera",
  "cat_elektronik_ac",
  "cat_elektronik_ac_portable",
  "cat_elektronik_air_cooler",
  "cat_elektronik_air_fryer",
  "cat_elektronik_air_purifier",
  "cat_elektronik_blender",
  "cat_elektronik_dispenser",
  "cat_elektronik_juicer",
  "cat_elektronik_kipas",
  "cat_elektronik_kulkas",
  "cat_elektronik_mesin_cuci",
  "cat_elektronik_microwave",
  "cat_elektronik_mixer",
  "cat_elektronik_oven",
  "cat_elektronik_rice_cooker",
  "cat_elektronik_setrika",
  "cat_elektronik_teko",
  "cat_elektronik_televisi",
  "cat_elektronik_toaster",
  "cat_elektronik_vacuum",
  "cat_fashion_anak_laki_baju_tidur",
  "cat_fashion_anak_laki_celana_panjang",
  "cat_fashion_anak_laki_celana_pendek",
  "cat_fashion_anak_laki_hoodie",
  "cat_fashion_anak_laki_jaket",
  "cat_fashion_anak_laki_kaos",
  "cat_fashion_anak_laki_kemeja",
  "cat_fashion_anak_laki_sepatu_sandal",
  "cat_fashion_anak_laki_sepatu_sneakers",
  "cat_fashion_anak_laki_setelan",
  "cat_fashion_anak_perempuan_blouse",
  "cat_fashion_anak_perempuan_dress",
  "cat_fashion_anak_perempuan_rok",
  "cat_fashion_anak_perempuan_sandal",
  "cat_fashion_anak_perempuan_setelan",
  "cat_fashion_anak_perempuan_sneakers",
  "cat_fashion_anak_tas_ransel",
  "cat_fashion_bayi_jumper",
  "cat_fashion_bayi_pakaian_laki",
  "cat_fashion_muslim_abaya",
  "cat_fashion_muslim_baju_koko",
  "cat_fashion_muslim_celana",
  "cat_fashion_muslim_gamis",
  "cat_fashion_muslim_hijab_instan",
  "cat_fashion_muslim_hijab_segi_empat",
  "cat_fashion_muslim_kaftan",
  "cat_fashion_muslim_mukena",
  "cat_fashion_muslim_pashmina",
  "cat_fashion_muslim_rok",
  "cat_fashion_muslim_sajadah",
  "cat_fashion_muslim_sarung",
  "cat_fashion_muslim_tunik",
  "cat_fashion_pria_batik_kemeja",
  "cat_fashion_pria_blazer",
  "cat_fashion_pria_boots",
  "cat_fashion_pria_cardigan",
  "cat_fashion_pria_celana_cargo",
  "cat_fashion_pria_celana_chino",
  "cat_fashion_pria_celana_dalam",
  "cat_fashion_pria_celana_jogger",
  "cat_fashion_pria_celana_pendek",
  "cat_fashion_pria_dompet",
  "cat_fashion_pria_hoodie",
  "cat_fashion_pria_ikat_pinggang",
  "cat_fashion_pria_jaket",
  "cat_fashion_pria_jas",
  "cat_fashion_pria_jeans",
  "cat_fashion_pria_kaos",
  "cat_fashion_pria_kemeja",
  "cat_fashion_pria_loafers",
  "cat_fashion_pria_sandal",
  "cat_fashion_pria_sneakers",
  "cat_fashion_pria_tas_ransel",
  "cat_fashion_pria_tas_selempang",
  "cat_fashion_pria_topi_baseball",
  "cat_fashion_seragam_bawahan",
  "cat_fashion_wanita_anting",
  "cat_fashion_wanita_blazer",
  "cat_fashion_wanita_blouse",
  "cat_fashion_wanita_boots",
  "cat_fashion_wanita_bra",
  "cat_fashion_wanita_cardigan",
  "cat_fashion_wanita_celana_dalam",
  "cat_fashion_wanita_celana_kulot",
  "cat_fashion_wanita_celana_panjang",
  "cat_fashion_wanita_celana_pendek",
  "cat_fashion_wanita_crop_top",
  "cat_fashion_wanita_dompet",
  "cat_fashion_wanita_flat_shoes",
  "cat_fashion_wanita_gelang",
  "cat_fashion_wanita_handbag",
  "cat_fashion_wanita_heels",
  "cat_fashion_wanita_hoodie",
  "cat_fashion_wanita_jeans",
  "cat_fashion_wanita_kalung",
  "cat_fashion_wanita_kaos",
  "cat_fashion_wanita_kebaya_brukat",
  "cat_fashion_wanita_kemeja",
  "cat_fashion_wanita_legging",
  "cat_fashion_wanita_maxi_dress",
  "cat_fashion_wanita_midi_dress",
  "cat_fashion_wanita_mini_dress",
  "cat_fashion_wanita_rok",
  "cat_fashion_wanita_sandal",
  "cat_fashion_wanita_sneakers",
  "cat_fashion_wanita_tank_top",
  "cat_fashion_wanita_tas_ransel",
  "cat_fashion_wanita_tas_selempang",
  "cat_fashion_wanita_tote",
  "cat_film_alat_musik_tradisional",
  "cat_film_bass_elektrik",
  "cat_film_drum_elektrik",
  "cat_film_drum_pad",
  "cat_film_gitar_akustik",
  "cat_film_gitar_elektrik",
  "cat_film_keyboard",
  "cat_film_piano_elektrik",
  "cat_film_ukulele",
  "cat_gaming_aksesoris_casing",
  "cat_gaming_aksesoris_joystick",
  "cat_gaming_nintendo",
  "cat_gaming_playstation",
  "cat_gaming_xbox",
  "cat_hp_aksesoris_charger",
  "cat_hp_aksesoris_hardcase",
  "cat_hp_aksesoris_holder",
  "cat_hp_aksesoris_kabel_data",
  "cat_hp_aksesoris_screen_protector",
  "cat_hp_aksesoris_softcase",
  "cat_hp_android",
  "cat_hp_ios",
  "cat_hp_powerbank",
  "cat_hp_smartband",
  "cat_hp_smartwatch",
  "cat_ibu_bayi_bantal_guling",
  "cat_ibu_bayi_bathtub",
  "cat_ibu_bayi_botol_susu",
  "cat_ibu_bayi_box_tidur",
  "cat_ibu_bayi_car_seat",
  "cat_ibu_bayi_gendongan",
  "cat_ibu_bayi_kursi_makan",
  "cat_ibu_bayi_minyak_telon",
  "cat_ibu_bayi_playmat",
  "cat_ibu_bayi_popok",
  "cat_ibu_bayi_sereal_bubur",
  "cat_ibu_bayi_shampoo",
  "cat_ibu_bayi_stroller",
  "cat_ibu_bayi_susu_bayi",
  "cat_kamera_360",
  "cat_kamera_action_camera",
  "cat_kamera_cctv",
  "cat_kamera_dslr",
  "cat_kamera_instan_printer",
  "cat_kamera_ip",
  "cat_kamera_mirrorless",
  "cat_kamera_pocket",
  "cat_kamera_spy",
  "cat_kecantikan_bedak",
  "cat_kecantikan_blush_on",
  "cat_kecantikan_catokan",
  "cat_kecantikan_cleanser",
  "cat_kecantikan_collagen",
  "cat_kecantikan_conditioner",
  "cat_kecantikan_cushion",
  "cat_kecantikan_eyeliner",
  "cat_kecantikan_eyeshadow",
  "cat_kecantikan_foundation",
  "cat_kecantikan_hair_dryer",
  "cat_kecantikan_krim_wajah",
  "cat_kecantikan_kuteks",
  "cat_kecantikan_lip_balm",
  "cat_kecantikan_lip_tint",
  "cat_kecantikan_lipstik",
  "cat_kecantikan_mascara",
  "cat_kecantikan_masker_wajah",
  "cat_kecantikan_pensil_alis",
  "cat_kecantikan_serum_mata",
  "cat_kecantikan_serum_wajah",
  "cat_kecantikan_shampoo",
  "cat_kecantikan_sunblock",
  "cat_kecantikan_toner",
  "cat_kesehatan_alat_diagnosa",
  "cat_kesehatan_alat_pijat",
  "cat_kesehatan_calcium",
  "cat_kesehatan_masker_medis",
  "cat_kesehatan_multivitamin",
  "cat_kesehatan_obat_herbal",
  "cat_kesehatan_suplemen_olahraga",
  "cat_kesehatan_termometer",
  "cat_kesehatan_vitamin_anak",
  "cat_kesehatan_vitamin_c",
  "cat_kesehatan_vitamin_d",
  "cat_kesehatan_vitamin_e",
  "cat_komik_anak",
  "cat_komik_manga",
  "cat_komputer_flashdisk",
  "cat_komputer_hdd_external",
  "cat_komputer_headset_gaming",
  "cat_komputer_keyboard",
  "cat_komputer_keyboard_gaming",
  "cat_komputer_laptop",
  "cat_komputer_laptop_gaming",
  "cat_komputer_macbook",
  "cat_komputer_microsd",
  "cat_komputer_monitor_led",
  "cat_komputer_mouse",
  "cat_komputer_mouse_gaming",
  "cat_komputer_mousepad_gaming",
  "cat_komputer_printer_inkjet",
  "cat_komputer_printer_laser",
  "cat_komputer_ram",
  "cat_komputer_router",
  "cat_komputer_ssd",
  "cat_komputer_tas_laptop",
  "cat_komputer_vga",
  "cat_komputer_webcam",
  "cat_lensa_kamera",
  "cat_lighting_flash_kamera",
  "cat_lighting_ring_light",
  "cat_mainan_action_figure",
  "cat_mainan_anak_edukasi",
  "cat_mainan_bayi_edukasi",
  "cat_mainan_board_game",
  "cat_mainan_boneka_beruang",
  "cat_mainan_boneka_karakter",
  "cat_mainan_diecast_mobil",
  "cat_mainan_diecast_motor",
  "cat_mainan_gundam",
  "cat_mainan_puzzle_jigsaw",
  "cat_mainan_rc_helikopter",
  "cat_mainan_rc_mobil",
  "cat_mainan_slime",
  "cat_makanan_beras_putih",
  "cat_makanan_biskuit",
  "cat_makanan_bumbu_masak",
  "cat_makanan_coklat",
  "cat_makanan_granola",
  "cat_makanan_gula",
  "cat_makanan_kacang",
  "cat_makanan_keripik",
  "cat_makanan_kopi_bubuk",
  "cat_makanan_mie_instan",
  "cat_makanan_oat",
  "cat_makanan_permen",
  "cat_makanan_roti",
  "cat_makanan_sambal",
  "cat_makanan_susu_bubuk",
  "cat_makanan_susu_uht",
  "cat_makanan_teh",
  "cat_makanan_tepung_terigu",
  "cat_makanan_yogurt",
  "cat_novel_fantasi",
  "cat_novel_indonesia",
  "cat_novel_misteri",
  "cat_novel_roman",
  "cat_novel_terjemahan",
  "cat_office_buku_tulis",
  "cat_office_cat_akrilik",
  "cat_office_gunting",
  "cat_office_kalkulator",
  "cat_office_map_binder",
  "cat_office_mesin_jahit",
  "cat_office_notebook",
  "cat_office_pensil",
  "cat_office_pensil_warna",
  "cat_office_pulpen",
  "cat_office_spidol",
  "cat_office_sticky_notes",
  "cat_olahraga_baju_renang_pria",
  "cat_olahraga_baju_renang_wanita",
  "cat_olahraga_bola_sepak",
  "cat_olahraga_dumbbell",
  "cat_olahraga_gym_ball",
  "cat_olahraga_helm_sepeda",
  "cat_olahraga_jersey_bola",
  "cat_olahraga_knee_pad",
  "cat_olahraga_legging_sport",
  "cat_olahraga_raket_badminton",
  "cat_olahraga_raket_tenis",
  "cat_olahraga_resistance_band",
  "cat_olahraga_sarung_tinju",
  "cat_olahraga_sepatu_badminton",
  "cat_olahraga_sepatu_bola",
  "cat_olahraga_sepatu_futsal",
  "cat_olahraga_sepatu_lari_pria",
  "cat_olahraga_sepatu_lari_wanita",
  "cat_olahraga_sepeda_gunung",
  "cat_olahraga_sepeda_statis",
  "cat_olahraga_shuttlecock",
  "cat_olahraga_sleeping_bag",
  "cat_olahraga_sport_bra",
  "cat_olahraga_tas_gunung",
  "cat_olahraga_tenda_camping",
  "cat_olahraga_treadmill",
  "cat_olahraga_yoga_mat",
  "cat_otomotif_helm_full_face",
  "cat_tablet_android",
  "cat_tablet_ios",
];

// =============================================================
// PRODUCT SLUGS — Di-load dari generated_product_data.json
// Di-generate oleh generate_seed_data.sh (query: stock > 100, limit 100)
// =============================================================
export const PRODUCT_SLUGS = _generatedData?.product_slugs ?? [];

// =============================================================
// PRODUCT IDs FOR CART — Di-load dari generated_product_data.json
// Stock > 500 supaya tidak habis selama load test
// Di-generate oleh generate_seed_data.sh (query: stock > 500, limit 30)
// =============================================================
export const PRODUCT_IDS_FOR_CART = _generatedData?.product_ids_for_cart ?? [];

// =============================================================
// SEARCH KEYWORDS — Kata kunci realistis dari dataset Tokopedia
// Dipilih berdasarkan nama kategori yang pasti ada di produk
// =============================================================
export const SEARCH_KEYWORDS = [
  "kaos",
  "kemeja",
  "celana",
  "sepatu",
  "tas",
  "jaket",
  "dress",
  "rok",
  "sandal",
  "hoodie",
  "jeans",
  "sneakers",
  "hijab",
  "gamis",
  "buku",
  "novel",
  "vitamin",
  "headphone",
  "earphone",
  "speaker",
  "laptop",
  "keyboard",
  "mouse",
  "kamera",
  "tripod",
  "rice cooker",
  "blender",
  "panci",
  "dumbbell",
  "raket",
];

// =============================================================
// SORT OPTIONS — Kombinasi valid sesuai productQuerySchema
// =============================================================
export const SORT_OPTIONS = [
  { sortBy: "price", sortOrder: "asc" },
  { sortBy: "price", sortOrder: "desc" },
  { sortBy: "sold_count", sortOrder: "desc" },
  { sortBy: "rating", sortOrder: "desc" },
  { sortBy: "created_at", sortOrder: "desc" },
];

// =============================================================
// ADMIN TEST PRODUCT — Template untuk product create di s05
// =============================================================
export const ADMIN_TEST_PRODUCT = {
  description:
    "k6 load test product — auto-deleted via soft-delete (isActive: false) after test",
  price: 99999,
  stock: 9999,
  discount: 0,
  images: [],
  location: "Jakarta",
};

// =============================================================
// UTILITY FUNCTIONS
// =============================================================
export function randomItem(arr) {
  if (!arr || arr.length === 0) return null;
  return arr[Math.floor(Math.random() * arr.length)];
}

export function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
